### ISSUE TITLE
[Question] When I upload images to list's description, error happen

### ISSUE THREAD

**Issue by rogerBridge** [go-vikunja/frontend#22] opened 2021-06-09 22:09 UTC
Hello Sir, your vikunja is really a fantastic app, recently, while using your app, I found a bug, when I upload image file to list's description, a bug will happen, in browser console:
![image](https://user-images.githubusercontent.com/17608761/121435768-fccfe280-c96e-11eb-8a26-eb93bdcfdc91.png)
In frontend:
![image](https://user-images.githubusercontent.com/17608761/121435821-0d805880-c96f-11eb-8070-8f7203126027.png)

my platform: 
client: linux x86 64, firefox 89.0;
server: docker-compose, follow your website's example;
If you need more info about this situation, please tell me : )
could u help me deal with this question? Thank you Sir!

**Comment by rogerBridge** [comment] 2021-06-09 22:11
PS: this error msg is circulate print in browser console

**Comment by kolaente** [comment] 2021-06-10 07:09
Hi :)

What Vikunja version is that? (There should be a message in the browser console)

Can you reproduce this on [try](https://try.vikunja.io)?

**Comment by rogerBridge** [comment] 2021-06-10 16:34
Hello Sir:
  This is the frontend version: Vikunja frontend version 0.17.0+47-34ded051d1, 
  Sir, when I upload image file to "try", error happend, show below:
![image](https://user-images.githubusercontent.com/17608761/121562996-8633f300-ca09-11eb-9ee1-e126fa7f9c45.png)
![image](https://user-images.githubusercontent.com/17608761/121563083-9f3ca400-ca09-11eb-8f1d-f667f7eca50a.png)
Thanks for response : )

**Comment by rogerBridge** [comment] 2021-06-11 07:07
I just retest it on "try", it worked, I guess maybe some static asset load error yesterday, the same time, I found a small issue, I add a list called: "test_list", and add a item called: "test_image_upload", when I click the attachment, it looks like miss token in request header so the api call is rejected by api server

**Comment by rogerBridge** [comment] 2021-06-11 07:13
"e is not defined" error message still exist in my environment, I guess maybe I did something wrong, I follow majority of  your instruct on vikunja website: "nginx -> (api + frontend)", but I add a layer, "caddy -> nginx -> (api + frontend)", I just use caddy point to nginx's port, just like: nginx associate local 127.0.0.1:8000, and caddy as a reverse proxy point to 127.0.0.1:8000(because caddy had very easy let's encrypt certificate apply and I had some app use caddy, I want make all of them in one place), I will visit nginx only as reverse proxy and try it later

**Comment by kolaente** [comment] 2021-06-11 10:45
> it looks like miss token in request header so the api call is rejected by api server

Anything in the server logs? Is the file created correctly in the db and on disk?

> I had some app use caddy, I want make all of them in one place), I will visit nginx only as reverse proxy and try it later

If you're running with docker behind caddy, you might want to check out [the caddy proxy examples](https://vikunja.io/docs/full-docker-example/#example-with-caddy-v2-as-proxy).

**Comment by rogerBridge** [comment] 2021-06-11 11:28
> Anything in the server logs? Is the file created correctly in the db and on disk?
Sir, I am sorry for my bad English and my bad expression, "try" is [try](https://try.vikunja.io), it is your website, so I could not know the server logs.
> I had some app use caddy, I want make all of them in one place), I will visit nginx only as reverse proxy and try it later
Thanks, Sir, I will follow your instruct to check out "the caddy proxy examples"

**Comment by rogerBridge** [comment] 2021-06-11 11:49
> > If you're running with docker behind caddy, you might want to check out the caddy proxy examples.
> Thanks, Sir, I will follow your instruct to check out "the caddy proxy examples"

Sir, I followed your instruct, and the issue still exists

**Comment by kolaente** [comment] 2021-06-11 12:34
> Sir, I am sorry for my bad English and my bad expression, "try" is try, it is your website, so I could not know the server logs.

Nothing to worry about, I'm not a native english speaker myself so I know that very well :slightly_smiling_face: 

I've looked at the list and task you created on try and the attachment was uploaded just fine. I can access it when clicking on it in the list, embedding works as well when adding a `!` in front of the generated markdown code when uploading through the editor (That's an upstream bug in the editor itself).

> Sir, I followed your instruct, and I update all vikunja images(vikunja/api:latest + vikunja/frontend:latest) and the issue still exists;

The configuration looks fine to me. It looks like you're able to access the frontend and upload files even though uploading itself fails. That means the caddy configuration is working fine.

About the permission error: The files folder you mounted to store the attachments (and other things) needs to be accessible to the user and group with the id 1000 for Vikunja to have access to it. Try running `chown 1000:1000 ./files -R` in the directory where the compose file is stored. After that, restart the container and try uploading an attachment again.

You can could change the uid and gid to match the value of some other user on your host system: https://vikunja.io/docs/install-backend/#files-volume

**Comment by rogerBridge** [comment] 2021-06-11 13:09
Wow, it worked, Thanks, Sir, and  I have a question, I had add docker to sudo group, so if its permisson group is: root:root, it should has permission to store file in my home directory, why it can't? did it say: docker usergroup is just docker usergroup, it is not root:root, it is equal to user:user group, so it has not permission to store file in user:user's folder, is it right?
ps: just a irrelavant question

**Comment by kolaente** [comment] 2021-06-11 13:14
While the docker daemon runs as root, Vikunja itself does not. Vikunja runs as `1000:1000` so if it wants to store files somewhere they have to be accessible to that user. I think you got the gist of it :slightly_smiling_face: 
There's a bit more info about docker's permission model here: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

I'm going to close this issue as your problem got resolved. Feel free to open a new one if you have other issues or [check out the forum](https://community.vikunja.io).

**Closed by kolaente** 2021-06-11 13:14 UTC

**Comment by rogerBridge** [comment] 2021-06-11 13:34
Thank you, Sir, I guess I understand why you design it, when I run `docker run vikunja/xxx`, vikunja/api detect who I am and my UID/GID, because I am not root:root, so it can't store file in a root:root directory, if I change the docker volume to a root:root directory, then the issue maybe I won't face : )

**Comment by rogerBridge** [comment] 2021-06-11 13:49
I found something in vikunja/api Dockerfile:
```Dockerfile
ENV PUID 1000
ENV PGID 1000
```
I guess it is the answer, before I am wrong, it associate docker usergroup and host usergroup;
thank you, Sir : )
