### ISSUE TITLE
After renaming a namespace, "Overview" shows the old name in front of tasks until you refresh.

### ISSUE THREAD

**Issue by SteveDinn** [go-vikunja/frontend#19] opened 2021-05-23 17:34 UTC
## To Reproduce
* Have lists & tasks in a namespace.
* Hit the overview tab.
* Rename the namespace.
* Hit the overview tab again.

Without a hard refresh, the "Overview" view will show the old name in front of the tasks from that namespace.

## Expected results
Whatever cache is holding the old name of the namespace should be updated or invalidated when a namespace is renamed. The Overview should always show up-to-date names for namespaces.

**Comment by kolaente** [comment] 2021-05-24 21:31
Yup, that sounds like a bug.
Can you reproduce this on [try](https://try.vikunja.io)?

**Comment by SteveDinn** [comment] 2021-05-24 22:31
Yes. I was able to reproduce it.

**Comment by SteveDinn** [comment] 2021-05-25 19:47
Should I have been writing these on https://kolaente.dev/vikunja/frontend/issues instead? 

I think this is basically the same bug but I just noticed that when you delete a namespace, it remains on the left-hand side until you refresh.

**Comment by kolaente** [comment] 2021-05-25 21:31
Reporting issues here is fine, but the development happens mostly in the Gitea repo. There may be one reported over there already but I'll try to keep these in sync.

**Comment by kolaente** [comment] 2021-05-26 14:30
The namespace name isn't even shown in the overview but I'm assuming you mean the list? Because that does not properly update. 

This one: 
![image](https://user-images.githubusercontent.com/13721712/119678219-a4adc200-be3f-11eb-8016-a023d0acf142.png)

**Comment by kolaente** [comment] 2021-05-26 14:47
Should be fixed in https://github.com/go-vikunja/frontend/commit/9d818921a7ca2f06a55ae056639eddd658ab9c99 - A new unstable release with a fix will be automatically released in ~30min. Feel free to reopen if the issue persists.

**Closed by kolaente** 2021-05-26 14:47 UTC
Labels: bug

**Comment by SteveDinn** [comment] 2021-05-26 15:21
Yes, that one, but also the far left-hand side where namespaces are listed. If you delete a namespace, it doesn't go away from the far left side.

![image](https://user-images.githubusercontent.com/3911507/119686501-c5185500-be1c-11eb-8688-d05455223faf.png)

**Comment by kolaente** [comment] 2021-05-26 15:42
Yup, that's the same category of bug. Fixed in https://github.com/go-vikunja/frontend/commit/9c799ab16179b1da90548f69d7f7bd65389554ce

Sometimes all that's needed to catch these rather obvious bugs is the eyes of a new user :)
