### ISSUE TITLE
[FR] Option to add subtask from within task details pannel

### ISSUE THREAD

**Issue by RoboMagus** [go-vikunja/frontend#43] opened 2022-03-10 10:10 UTC
Currently it seems to be only possible to add a 'subtask' relation for existing tasks using the 'add task relations' option.
However it would be a great improvement to be able to add such a subtask from the same menu as well, if a task with the provided name does not already exist.

**Comment by kolaente** [comment] 2022-03-10 20:20
That already works. What version are you using? Can you reproduce this on [try](https://try.vikunja.io)?

**Comment by RoboMagus** [comment] 2022-03-11 09:16
Ah, yes. I see the problem now.

I am using the latest greatest versions for all Vikunja containers, and I could reproduce this in `try`.
The scenario that I ran into was typing the name of the Subtask and then hitting the button `add a new task relation`, which would then throw me an error `cannot read properties of null (reading 'id')`.
After trying some variations on this, when just hitting `enter` after filling in the subtask name it works as intended.

I expected the on screen button and enter to perform the same action though. Is that not the case?

**Comment by kolaente** [comment] 2022-03-22 19:19
Interesting, I was not able to reproduce the error about the missing property - I got an error the task would not exist (which kind of makes sense, given that Vikunja didn't create it on the fly).

Can you provide exact steps to reproduce the bug?

How should this work? The same when pressing enter and clicking "Add a new task relation"?

**Comment by RoboMagus** [comment] 2022-03-28 19:49
When trying to reproduce now I no longer get the same error message. This may have changed when I've updated the vikunja docker images. 

For the record, what I would do is:
1. Open an existing task in the kanban board
2. From the sidebar select `add task relations`
3. Enter a subtask title in the textbox.
4. Select `subtask` from the dropdown list.
5. Click `Add a new task relation`.

When going through the same steps now I get `Request failed with status code 404. The list task does not exist.`

**Comment by kolaente** [comment] 2022-04-02 11:56
Should be fixed in dfed1f438a168606617d2ecef55cd83ff724201f - please verify with the next unstable release in ~30 min if the fix works for you.

**Closed by kolaente** 2022-04-02 11:56 UTC
