### ISSUE TITLE
Background image flickers when task is autosaved

### ISSUE THREAD

**Issue by canadaduane** [go-vikunja/frontend#57] opened 2022-06-09 21:21 UTC
When viewing a task overlay in the kanban view, if the list has a background, the background image will "flicker" each time the task is autosaved. It happens every 1-2 seconds if the Description is being edited.

![image](https://user-images.githubusercontent.com/129/172946917-6916c417-f121-4120-86e6-a944fd06888d.png)

**Comment by kolaente** [comment] 2022-06-11 12:25
Can you reproduce this on [try](https://try.vikunja.io)?

**Comment by canadaduane** [comment] 2022-06-11 14:23
No, it seems to be fine there. I also note that the autosave timeout seems to wait until typing stops, rather than re-saving several times while typing.

**Comment by kolaente** [comment] 2022-06-12 12:49
>  I also note that the autosave timeout seems to wait until typing stops, rather than re-saving several times while typing.

That's by design to avoid too many requests. If you click on save it will save whatever is in the edit box right away.

I'll close this issue since the original bug seems to be fixed on the newest unstable (try) already.

**Closed by kolaente** 2022-06-12 12:49 UTC
