### ISSUE TITLE
Side by Side editor feature breaks everything

### ISSUE THREAD

**Issue by thelicato** [go-vikunja/frontend#92] opened 2022-11-15 09:48 UTC
### Description

When using the editor (i.e. writing a description, posting a comment and so on) if I click on the "Side by side" icon it becomes full screen and it is impossible to deactivate it. The only working solution is to refresh the page.

### Vikunja Frontend Version

0.20.1

### Vikunja API Version

0.20.1

### Browser and version

Chrome Version 107.0.5304.110 (Official Build) (64-bit)

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![Screenshot from 2022-11-15 10-47-35](https://user-images.githubusercontent.com/20096272/201887173-a191f27b-4a7e-40ad-9997-cf2f8a4b6f40.png)
![Screenshot from 2022-11-15 10-47-49](https://user-images.githubusercontent.com/20096272/201887184-2518e64c-bcef-4adb-9188-19df5e10aa9f.png)

**Comment by dpschen** [comment] 2022-11-15 10:00
You can close it via <kbd>esc</kbd>.

Still not, how it should be!
The toolbar is hidden behind the navigation. Is this how you made the second screenshot @thelicato?

We are in the process of replacing our editor with [TipTap](https://tiptap.dev/) (also see wip pull request: https://kolaente.dev/vikunja/frontend/pulls/2222). I guess this is an error big enough so that it makes sense to fix it before we go merge that.

To reveal the editor navigation, we only have to move it down, that's an easy fix.

But if you click then the Side-by-side button again it stays in fullscreen but switches to the single column (markdown) mode.
If you click the button another time you go back to the described two column fullscreen.

@kolaente Do you remember the user was intended to get out of this mode (aside of <kbd>esc</kbd>)? Was there a close button or something?

Also I'm not sure if opening the editor in fullscreen is what one would suspect to happen when clicking on the side-by-side button.

**Comment by thelicato** [comment] 2022-11-15 10:17
The second screenshot is taken after clicking on the _Side by side_ button inside a Task modal. Yep it's a bit confusing for the user

**Comment by dpschen** [comment] 2022-11-15 10:46
Ahh, that's why the main navigation doesn't overlay the editor menu.

**Comment by kolaente** [comment] 2022-11-15 13:43
> @kolaente Do you remember the user was intended to get out of this mode (aside of esc)? Was there a close button or something?

AFAIK there should be a button in the toolbar to get out again. I didn't implement this though, that's a feature of the editor.

The fix should be to make the toolbar visible. If that's too much work I think we can get by with just removing the button in the editor toolbar alltogether as we'll replace the editor anyway.

**Comment by dpschen** [comment] 2022-11-15 17:18
I found a setting in EasyMDE (our current editor) which lets you disable the going to fullscreen in the side-by-side mode.
I made a pull request, where you can check out in the preview how that would look:
https://kolaente.dev/vikunja/frontend/pulls/2710

What do you think? Should we disable fullscreen?

**Closed** 2022-11-16 14:37 UTC
Labels: bug
