### ISSUE TITLE
Bug: Some subtasks don't show up, likely pagination issue.

### ISSUE THREAD

**Issue by from-nibly** [go-vikunja/frontend#136] opened 2023-12-20 21:46 UTC
### Description

When adding subtasks onto a project through the task details page, I noticed that some of the tasks aren't showing up in the list. Also i now have multiple pages in the project, but the second page doesn't have any tasks that show up.

### Vikunja Frontend Version

0.22.0

### Vikunja API Version

0.22.0

### Browser and version

Firefox 119.0.1

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![Selection_437](https://github.com/go-vikunja/frontend/assets/3860803/739a6111-c240-4ca6-a8c8-495976c14c03)
![image](https://github.com/go-vikunja/frontend/assets/3860803/cc67b576-b21b-4d9d-9b1e-40cde37393b8)

If this still exists at time of reading the link to this project is https://try.vikunja.io/projects/23/list?page=2

I created tasks with 11 subtasks over and over until it appeared.

it looks like there are 50 tasks before it paginates and stops showing up

Here's the yoo task with all of the actual subtasks

![image](https://github.com/go-vikunja/frontend/assets/3860803/c3133f88-4221-4adc-95ca-e271c8a75607)

**Comment by from-nibly** [comment] 2023-12-20 22:04
Actually I'm adding more and more tasks to my list and it looks like there are several pagination + subtask related issues. 

I think this is all frontend related since the api Seems to be returning all subtasks just fine in the API calls I see in the browser.

Like right now I'm seeing that even after pushing some tasks to the second page, Some parent tasks now contain all of their subtasks while others don't

**Comment by kolaente** [comment] 2023-12-21 13:19
Which of the tasks are actually missing? Only tasks which are the subtask of another task?

**Comment by from-nibly** [comment] 2023-12-21 13:54
Yes parent tasks all seem to appear. It's just the subtasks that are missing as far as I can tell.

**Comment by kolaente** [comment] 2023-12-21 14:39
Are the subtasks definitely missing or do they show up as nested below their parent?

**Comment by from-nibly** [comment] 2023-12-21 15:01
They look like the screenshots above. The tasks definitely exist. They show up in the details page. They don't appear in the project list page though. 

The examples should also be in the "try" domain for you to explore.

**Comment by from-nibly** [comment] 2023-12-21 15:03
> The examples should also be in the "try" domain for you to explore. 

Jk they are gone.

**Comment by kolaente** [comment] 2023-12-23 13:49
Do they show up as nested below their parent in the project list?

**Comment by from-nibly** [comment] 2023-12-23 13:52
No that's what the bug is about.  Some of them do some of them don't.

They show up fine in the details page, the kanban board, and the table, but they don't show up nested below their parents on the project list. The screenshots should help illustrate what I'm talking about.

**Comment by from-nibly** [comment] 2023-12-23 13:53
I guess for a little more clarification. They don't show up anywhere on the project list nested or otherwise.

**Comment by kolaente** [comment] 2024-01-15 20:49
I've pushed a potential fix in 664bf0a5f48ba872236de6af9c2735e68b47b4b7 - can you check with the next unstable build if the problem went away?

**Comment by kolaente** [comment] 2024-01-26 22:57
Closing as resolved, since I'm unable to reproduce this any more. Please ping if you think this is still a problem.

**Closed by kolaente** 2024-01-26 22:57 UTC
