### ISSUE TITLE
"Invalid date" displayed in Gantt chart

### ISSUE THREAD

**Issue by Themisphere** [go-vikunja/frontend#59] opened 2022-06-10 10:13 UTC
Hi,
When displaying the Gantt chart, I have "Invalid date" instead of the relevant Month name on the top of the chart.
Any idea why and how to solve the issue?
Thank you,

<img width="1391" alt="Capture d’écran 2022-06-10 à 12 08 10" src="https://user-images.githubusercontent.com/74971917/173043862-d156a1f7-cad5-44a2-861e-5ac609952732.png">

**Comment by kolaente** [comment] 2022-06-11 12:20
What browser and version are you using?

What locale and time zone is your os set to?

Which Vikunja version are you using?
Can you reproduce this on [try](https://try.vikunja.io)?

**Comment by Themisphere** [comment] 2022-06-14 20:53
Hi,

I'm using Safari browser on Mac OS.
Local time zone is set to Europe/Luxembourg (CET).
I'm using Vikunja Version : 0.18.2 - API version: v0.18.1

I cannot reproduce it on the "Try" website. I can't see any date displayed above the different dates of the month.

<img width="1302" alt="Capture d’écran 2022-06-14 à 22 52 27" src="https://user-images.githubusercontent.com/74971917/173686639-8db1e7d3-1f74-47b7-89fd-1fa994308591.png">

**Comment by kolaente** [comment] 2022-06-16 16:01
What Safari and MacOS version are you using?

**Comment by Themisphere** [comment] 2022-06-21 22:12
Using Safari Version 15.5 (17613.2.7.1.8)
MacOS 12.4

Ok, let's wait for next release.

**Comment by kolaente** [comment] 2022-07-04 15:47
I was able to reproduce that problem with browserstack. Don't know why it won't work though, will do some more digging.

**Comment by Themisphere** [comment] 2022-07-04 15:56
Thank you Kolaente

**Comment by kolaente** [comment] 2022-07-08 14:41
Should be fixed in 40b30079c1f02aa24a21fe359f451419f93c1d35 - please test on [try](https://try.vikunja.io) again in ~30 min if the problem went away.

**Closed** 2022-07-08 14:40 UTC
Labels: bug

**Comment by kolaente** [comment] 2022-07-08 15:24
You could switch your instance to the [`unstable` channel](https://vikunja.io/docs/versions/). Or wait for the next release.

**Comment by tomtjes** [comment] 2022-10-05 13:33
Adding to this issue because it seems related. I'm also on Safari/MacOS and the month in the Gantt chart is one month off. September is called August, October is called September and so on.
Frontend Version: 0.19.1
API Version: v0.19.2
Seeing the same issue on try.
