### ISSUE TITLE
Quick add in Overview tab defaulting to archived list

### ISSUE THREAD

**Issue by MildlyInterested** [go-vikunja/frontend#97] opened 2022-12-07 22:03 UTC
### Description

1. Archive all current lists (I suspect you only need to archive the one you started out with)
2. Create a new list
3. Go to "Overview" and try to add task in the "Add a new task" interface, e.g. `*Test Dishes`
4. Click on "Add", error will pop up in bottom left informing you that you can't add tasks to archived lists. (Error in Screenshots)

It would probably be best if one could select a "default" list where tasks get added to if no list is specified.

### Vikunja Frontend Version

0.20.1

### Vikunja API Version

0.20.1

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/57712666/206305584-225ee1d9-486d-4135-adda-379b67c1ef8a.png)

**Comment by dpschen** [comment] 2022-12-08 11:51
@MildlyInterested There is a settings for the default list in `Settings` / `General Settings`:

<img width="1028" alt="The General Settings page of Vikunja on https://try.vikunja.io" src="https://user-images.githubusercontent.com/6173598/206439454-f48721b8-c6ba-4978-b66e-91393fd945d3.png">

 
@kolaente:
My guess is that it shouldn't be possible to archive the default list. Also it shouldn't be possible to mark a list as default that is archived (unsure if that's currently possible).

**Comment by kolaente** [comment] 2022-12-08 14:10
>  My guess is that it shouldn't be possible to archive the default list. Also it shouldn't be possible to mark a list as default that is archived (unsure if that's currently possible).

yeah that should be the fix. Right now it is possible to set an archived list as the default or to archive the default list.

**Comment by MildlyInterested** [comment] 2022-12-08 20:31
Not sure how I missed that settings, thanks! Should I close the issue then?

**Comment by kolaente** [comment] 2022-12-08 22:12
If you feel like the problem is solved, yes please close the issue.

**Comment by dpschen** [comment] 2022-12-09 13:32
@kolaente Do we have tickets for the mentioned problems?

**Closed** 2022-12-09 14:11 UTC
Labels: bug
